# Generated by Django 3.2.10 on 2021-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211226_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='Опрос', max_length=80, verbose_name='Наименованеие опроса'),
        ),
    ]
